// Terraform code generation
function generateTerraform(targetNodes, targetCloud) {
  const cloud = targetCloud || (targetNodes.length > 0 ? targetNodes[0].cloud : 'aws');
  
  const main = generateMain(targetNodes, cloud);
  const variables = generateVariables(cloud);
  const outputs = generateOutputs(targetNodes, cloud);
  
  return { main, variables, outputs };
}

function generateMain(nodes, cloud) {
  if (nodes.length === 0) {
    return `# No resources added yet.\n# Drag services onto the canvas to generate Terraform code.\n\n# Provider configuration\nterraform {\n  required_version = ">= 1.5.0"\n  required_providers {\n    ${getProviderBlock(cloud)}\n  }\n}\n\nprovider "${getProviderName(cloud)}" {\n  ${getProviderConfig(cloud)}\n}`;
  }
  
  let code = `# Generated by CloudShift\n# Architecture: ${nodes.length} resource${nodes.length !== 1 ? 's' : ''}\n# Cloud: ${cloud.toUpperCase()}\n\n`;
  code += `terraform {\n  required_version = ">= 1.5.0"\n  required_providers {\n    ${getProviderBlock(cloud)}\n  }\n}\n\n`;
  code += `provider "${getProviderName(cloud)}" {\n  ${getProviderConfig(cloud)}\n}\n\n`;
  
  // Group by type for better organization
  const byCategory = {};
  nodes.forEach(n => {
    const cat = n.service.category || 'other';
    if (!byCategory[cat]) byCategory[cat] = [];
    byCategory[cat].push(n);
  });
  
  for (const cat in byCategory) {
    code += `# ── ${cat.toUpperCase()} ────────────────────────────\n\n`;
    byCategory[cat].forEach(node => {
      code += generateResource(node, cloud);
      code += '\n';
    });
  }
  
  return code;
}

function generateResource(node, cloud) {
  const resName = sanitizeName(node.label);
  const tfType = node.service.tf;
  
  let attrs = getDefaultAttributes(node.service.id, cloud, resName);
  
  return `resource "${tfType}" "${resName}" {\n${attrs}\n}\n`;
}

function getDefaultAttributes(serviceId, cloud, name) {
  const indent = '  ';
  const attrMap = {
    // AWS
    ec2: `${indent}ami           = var.ami_id\n${indent}instance_type = "t3.micro"\n${indent}key_name      = var.key_name\n\n${indent}tags = {\n${indent}  Name        = "${name}"\n${indent}  Environment = var.environment\n${indent}}`,
    lambda: `${indent}function_name = "${name}"\n${indent}role          = aws_iam_role.lambda_role.arn\n${indent}handler       = "index.handler"\n${indent}runtime       = "nodejs18.x"\n${indent}filename      = "function.zip"\n\n${indent}environment {\n${indent}  variables = {\n${indent}    ENVIRONMENT = var.environment\n${indent}  }\n${indent}}`,
    s3: `${indent}bucket        = "${name}-bucket"\n${indent}force_destroy = false\n\n${indent}versioning {\n${indent}  enabled = true\n${indent}}\n\n${indent}server_side_encryption_configuration {\n${indent}  rule {\n${indent}    apply_server_side_encryption_by_default {\n${indent}      sse_algorithm = "AES256"\n${indent}    }\n${indent}  }\n${indent}}\n\n${indent}tags = {\n${indent}  Name        = "${name}"\n${indent}  Environment = var.environment\n${indent}}`,
    rds: `${indent}identifier        = "${name}-db"\n${indent}engine            = "mysql"\n${indent}engine_version    = "8.0"\n${indent}instance_class    = "db.t3.micro"\n${indent}allocated_storage = 20\n${indent}db_name           = var.db_name\n${indent}username          = var.db_username\n${indent}password          = var.db_password\n${indent}skip_final_snapshot = true\n\n${indent}tags = {\n${indent}  Name        = "${name}"\n${indent}  Environment = var.environment\n${indent}}`,
    dynamodb: `${indent}name           = "${name}-table"\n${indent}billing_mode   = "PAY_PER_REQUEST"\n${indent}hash_key       = "id"\n\n${indent}attribute {\n${indent}  name = "id"\n${indent}  type = "S"\n${indent}}\n\n${indent}tags = {\n${indent}  Name        = "${name}"\n${indent}  Environment = var.environment\n${indent}}`,
    vpc: `${indent}cidr_block           = "10.0.0.0/16"\n${indent}enable_dns_hostnames = true\n${indent}enable_dns_support   = true\n\n${indent}tags = {\n${indent}  Name        = "${name}"\n${indent}  Environment = var.environment\n${indent}}`,
    eks: `${indent}name     = "${name}-cluster"\n${indent}role_arn = aws_iam_role.eks_role.arn\n${indent}version  = "1.28"\n\n${indent}vpc_config {\n${indent}  subnet_ids = var.subnet_ids\n${indent}}\n\n${indent}tags = {\n${indent}  Name        = "${name}"\n${indent}  Environment = var.environment\n${indent}}`,
    alb: `${indent}name               = "${name}-alb"\n${indent}internal           = false\n${indent}load_balancer_type = "application"\n${indent}security_groups    = var.security_group_ids\n${indent}subnets            = var.subnet_ids\n\n${indent}tags = {\n${indent}  Name        = "${name}"\n${indent}  Environment = var.environment\n${indent}}`,
    sqs: `${indent}name                      = "${name}-queue"\n${indent}delay_seconds             = 0\n${indent}max_message_size          = 262144\n${indent}message_retention_seconds = 86400\n${indent}visibility_timeout_seconds = 30\n\n${indent}tags = {\n${indent}  Name        = "${name}"\n${indent}  Environment = var.environment\n${indent}}`,
    sns: `${indent}name = "${name}-topic"\n\n${indent}tags = {\n${indent}  Name        = "${name}"\n${indent}  Environment = var.environment\n${indent}}`,
    iam: `${indent}name = "${name}-role"\n\n${indent}assume_role_policy = jsonencode({\n${indent}  Version = "2012-10-17"\n${indent}  Statement = [{\n${indent}    Action = "sts:AssumeRole"\n${indent}    Effect = "Allow"\n${indent}    Principal = {\n${indent}      Service = "ec2.amazonaws.com"\n${indent}    }\n${indent}  }]\n${indent}})`,
    cloudfront: `${indent}enabled             = true\n${indent}default_root_object = "index.html"\n\n${indent}origin {\n${indent}  domain_name = aws_s3_bucket.main.bucket_regional_domain_name\n${indent}  origin_id   = "S3Origin"\n${indent}}\n\n${indent}default_cache_behavior {\n${indent}  allowed_methods  = ["GET", "HEAD"]\n${indent}  cached_methods   = ["GET", "HEAD"]\n${indent}  target_origin_id = "S3Origin"\n${indent}  viewer_protocol_policy = "redirect-to-https"\n\n${indent}  forwarded_values {\n${indent}    query_string = false\n${indent}    cookies { forward = "none" }\n${indent}  }\n${indent}}`,
    
    // Azure
    az_vm: `${indent}name                  = "${name}-vm"\n${indent}resource_group_name   = azurerm_resource_group.main.name\n${indent}location              = var.location\n${indent}size                  = "Standard_B1s"\n${indent}admin_username        = var.admin_username\n\n${indent}network_interface_ids = [azurerm_network_interface.main.id]\n\n${indent}os_disk {\n${indent}  caching              = "ReadWrite"\n${indent}  storage_account_type = "Standard_LRS"\n${indent}}\n\n${indent}source_image_reference {\n${indent}  publisher = "Canonical"\n${indent}  offer     = "UbuntuServer"\n${indent}  sku       = "18.04-LTS"\n${indent}  version   = "latest"\n${indent}}`,
    az_functions: `${indent}name                       = "${name}-func"\n${indent}resource_group_name        = azurerm_resource_group.main.name\n${indent}location                   = var.location\n${indent}service_plan_id            = azurerm_service_plan.main.id\n${indent}storage_account_name       = azurerm_storage_account.main.name\n${indent}storage_account_access_key = azurerm_storage_account.main.primary_access_key`,
    az_blob: `${indent}name                     = "${name}storage"\n${indent}resource_group_name      = azurerm_resource_group.main.name\n${indent}location                 = var.location\n${indent}account_tier             = "Standard"\n${indent}account_replication_type = "GRS"\n\n${indent}tags = {\n${indent}  environment = var.environment\n${indent}}`,
    
    // GCP
    gce: `${indent}name         = "${name}-instance"\n${indent}machine_type = "e2-micro"\n${indent}zone         = var.zone\n\n${indent}boot_disk {\n${indent}  initialize_params {\n${indent}    image = "debian-cloud/debian-11"\n${indent}  }\n${indent}}\n\n${indent}network_interface {\n${indent}  network = google_compute_network.main.id\n${indent}  access_config {}\n${indent}}`,
    gcf: `${indent}name        = "${name}-function"\n${indent}description = "Cloud Function"\n${indent}runtime     = "nodejs18"\n${indent}region      = var.region\n\n${indent}build_config {\n${indent}  runtime     = "nodejs18"\n${indent}  entry_point = "handler"\n${indent}  source {\n${indent}    storage_source {\n${indent}      bucket = google_storage_bucket.main.name\n${indent}      object = "function.zip"\n${indent}    }\n${indent}  }\n${indent}}`,
    gcs: `${indent}name          = "${name}-bucket"\n${indent}location      = var.region\n${indent}force_destroy = false\n\n${indent}versioning {\n${indent}  enabled = true\n${indent}}\n\n${indent}labels = {\n${indent}  environment = var.environment\n${indent}}`,
  };
  
  return attrMap[serviceId] || `${indent}# Configure ${serviceId} settings\n${indent}# Refer to Terraform documentation for required attributes`;
}

function getProviderName(cloud) {
  return { aws: 'aws', azure: 'azurerm', gcp: 'google' }[cloud];
}

function getProviderBlock(cloud) {
  const blocks = {
    aws: `aws = {\n      source  = "hashicorp/aws"\n      version = "~> 5.0"\n    }`,
    azure: `azurerm = {\n      source  = "hashicorp/azurerm"\n      version = "~> 3.0"\n    }`,
    gcp: `google = {\n      source  = "hashicorp/google"\n      version = "~> 4.0"\n    }`
  };
  return blocks[cloud];
}

function getProviderConfig(cloud) {
  const configs = {
    aws: `region = var.aws_region\n\n  # Configure credentials via environment variables:\n  # AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY`,
    azure: `features {}\n\n  # Configure via environment:\n  # ARM_SUBSCRIPTION_ID, ARM_CLIENT_ID, ARM_CLIENT_SECRET, ARM_TENANT_ID`,
    gcp: `project = var.project_id\n  region  = var.region\n\n  # Configure via: gcloud auth application-default login`
  };
  return configs[cloud];
}

function generateVariables(cloud) {
  const varBlocks = {
    aws: `variable "aws_region" {\n  description = "AWS region"\n  type        = string\n  default     = "us-east-1"\n}\n\nvariable "environment" {\n  description = "Deployment environment"\n  type        = string\n  default     = "production"\n}\n\nvariable "ami_id" {\n  description = "EC2 AMI ID"\n  type        = string\n  default     = "ami-0c55b159cbfafe1f0"\n}\n\nvariable "key_name" {\n  description = "EC2 Key Pair name"\n  type        = string\n}\n\nvariable "db_name" {\n  description = "Database name"\n  type        = string\n  default     = "appdb"\n}\n\nvariable "db_username" {\n  description = "Database username"\n  type        = string\n  sensitive   = true\n}\n\nvariable "db_password" {\n  description = "Database password"\n  type        = string\n  sensitive   = true\n}\n\nvariable "subnet_ids" {\n  description = "List of subnet IDs"\n  type        = list(string)\n  default     = []\n}\n\nvariable "security_group_ids" {\n  description = "List of security group IDs"\n  type        = list(string)\n  default     = []\n}`,
    azure: `variable "location" {\n  description = "Azure region"\n  type        = string\n  default     = "East US"\n}\n\nvariable "environment" {\n  description = "Deployment environment"\n  type        = string\n  default     = "production"\n}\n\nvariable "admin_username" {\n  description = "VM admin username"\n  type        = string\n  default     = "adminuser"\n}`,
    gcp: `variable "project_id" {\n  description = "GCP Project ID"\n  type        = string\n}\n\nvariable "region" {\n  description = "GCP region"\n  type        = string\n  default     = "us-central1"\n}\n\nvariable "zone" {\n  description = "GCP zone"\n  type        = string\n  default     = "us-central1-a"\n}\n\nvariable "environment" {\n  description = "Deployment environment"\n  type        = string\n  default     = "production"\n}`
  };
  return varBlocks[cloud] || varBlocks.aws;
}

function generateOutputs(nodes, cloud) {
  if (nodes.length === 0) return `# Outputs will be generated based on your architecture`;
  
  let code = `# Outputs\n\n`;
  nodes.slice(0, 6).forEach(node => {
    const resName = sanitizeName(node.label);
    const tfType = node.service.tf;
    code += `output "${resName}_id" {\n  description = "ID of ${node.label}"\n  value       = ${tfType}.${resName}.id\n}\n\n`;
  });
  return code;
}

function sanitizeName(str) {
  return str.toLowerCase().replace(/[^a-z0-9_]/g, '_').replace(/^_+|_+$/g, '') || 'resource';
}

function initTerraform() {
  const modal = document.getElementById('terraform-modal');
  let currentTab = 'main';
  let currentTf = {};
  
  document.getElementById('btn-terraform').addEventListener('click', () => {
    currentTf = generateTerraform(nodes, nodes[0]?.cloud || 'aws');
    showTfContent(currentTf.main);
    modal.classList.remove('hidden');
  });
  
  document.getElementById('close-terraform').addEventListener('click', () => modal.classList.add('hidden'));
  modal.addEventListener('click', (e) => { if (e.target === modal) modal.classList.add('hidden'); });
  
  document.querySelectorAll('.modal-tab').forEach(tab => {
    tab.addEventListener('click', () => {
      currentTab = tab.dataset.tab;
      document.querySelectorAll('.modal-tab').forEach(t => t.classList.remove('active'));
      tab.classList.add('active');
      showTfContent(currentTf[currentTab] || '');
    });
  });
  
  document.getElementById('btn-copy-tf').addEventListener('click', () => {
    const content = document.getElementById('tf-content').textContent;
    navigator.clipboard.writeText(content).then(() => showToast('Copied to clipboard!'));
  });
  
  document.getElementById('btn-download-tf').addEventListener('click', () => {
    const content = document.getElementById('tf-content').textContent;
    const blob = new Blob([content], { type: 'text/plain' });
    const a = document.createElement('a'); a.href = URL.createObjectURL(blob);
    a.download = currentTab + '.tf'; a.click();
    showToast('Downloaded ' + currentTab + '.tf');
  });
}

function showTfContent(code) {
  const el = document.getElementById('tf-content');
  el.innerHTML = syntaxHighlight(code);
}

function syntaxHighlight(code) {
  return code
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/(#[^\n]*)/g, '<span class="tf-comment">$1</span>')
    .replace(/\b(resource|variable|output|provider|terraform|required_providers|required_version|source|version)\b/g, '<span class="tf-keyword">$1</span>')
    .replace(/"([^"]+)"/g, (m, p) => {
      if (p.includes('\n')) return m;
      return `<span class="tf-string">"${p}"</span>`;
    })
    .replace(/\b(true|false|null)\b/g, '<span class="tf-value">$1</span>');
}
